### ISSUE TITLE
Daily log

### ISSUE THREAD

**Issue by serin9** [Mind-Palace/sweetdream#1]
- commit 링크
- 테크블로그/논문/글 정리
- any 공부의 증거

**Comment by serin9** [comment]
[chrome extension: simple tab initial commit](https://github.com/serin9/chrome-extensions/commit/5dbc11b07283374f619954d19eb906ead3c333fe)

**Comment by magarage** [comment]
@serin9 어떤거 만드는거야?

**Comment by magarage** [comment]
https://github.com/magarage/mysite/commit/a003fe328ec901c3686798ef18e30c8f06e68df7

**Comment by serin9** [comment]
오늘은 자바스크립트 기초 공부 ㅎㅎ
막상하려니 기억이 아무것도 나질 않아서.. 

p.s. 아 12시 전에 업뎃할걸 ㅎㅎㅎ

**Comment by magarage** [comment]
장고 1권은 다 봤당..
이제 2권 볼차례 ㅎㅎ 재밌네 😄 
https://github.com/magarage/mysite/commits/master
https://github.com/Mind-Palace/configurations/commit/6c59aa1127a4f3608d4ff543c1068d565c22b954

**Comment by serin9** [comment]
오 ㅎㅎ 굳굳 ㅎㅎ 
매일 하기 진짜 어렵다 ㅋㅋㅋ
https://github.com/serin9/chrome-extensions/commit/eff6555111cde5bd767aa2411c2b2cbd00d2780f

**Comment by serin9** [comment]
어제 한 것! https://github.com/serin9/chrome-extensions/commit/2c6e638fc964ca4f34b85b055adff61a68302ade

**Comment by magarage** [comment]
https://github.com/Mind-Palace/mysite/commit/75fb6b119fb9ab28d0b89182af58348dcb933fc8
https://github.com/Mind-Palace/mysite/commit/e763a5159c255f0f148233a3081bfb4346612b50

**Comment by serin9** [comment]
https://github.com/serin9/chrome-extensions/issues/1#issuecomment-282735060

**Comment by serin9** [comment]
https://github.com/serin9/chrome-extensions/commit/ec71bb1d37ed5d69398dd7562abd22619b4387c0

**Comment by magarage** [comment]
https://github.com/Mind-Palace/mysite/commit/ea4e328251fbbfee8459a337bc18257c5b1febb8

**Comment by magarage** [comment]
https://github.com/Mind-Palace/mysite/commit/a32fd6a77e0aea7c3861d2aff5998135c0873536

**Comment by magarage** [comment]
장고 2권 챕터2까지.. 여기까진 1권 복습느낌..
https://github.com/Mind-Palace/mysite/commit/ea05c098a2bbeb80d6a195af6ad05e745c5059ee
vim python 설정 중.
https://github.com/Mind-Palace/configurations/commit/ca566fedaf1a8fd0d0500c130ffd517ed619299e

**Comment by magarage** [comment]
https://github.com/Mind-Palace/mysite/commit/35b3fc5ec079f6343ee62624ff9412a8978f8e06

**Comment by magarage** [comment]
https://github.com/Mind-Palace/mysite/commit/f48c3c72d022a935a290d665b7e8fa78fb292183

**Comment by serin9** [comment]
아.... ㅋㅋㅋ 시간이 이렇게 많이 지났네 ㅋㅋㅋㅋ

**Comment by magarage** [comment]
아 뭐야 낚였어 ㅋㅋ 
뭐 올린줄 ㅋㅋ

**Comment by serin9** [comment]
휴가 가면서 너무 쉼 ㅋㅋㅋ 오늘부터 다시 해야쥡! ㅋㅋ

**Comment by serin9** [comment]
https://github.com/serin9/chrome-extensions/commit/06dfc1aded54731b2f4626c7277329b61e6bd7e1

**Comment by magarage** [comment]
서버설정 추가
https://github.com/Mind-Palace/configurations/commits/master
장고 챕터3 완료
https://github.com/Mind-Palace/mysite/commits/master

**Comment by magarage** [comment]
스칼라 코세라 강의 수강을 시작하였습니다..
코세라에 한글 자막도 나오고 좋아졌네~
학습 진행상황은 아래 링크에 업데이트함 ㅎ
https://github.com/magarage/practice/issues/8

**Comment by magarage** [comment]
여기에 안남기니 서로 하는지 안하는지 알 수가 없구나.. ㅎㅎㅎ

**Comment by magarage** [comment]
@Mind-Palace
참조 테스트

**Comment by serin9** [comment]
다시 자바스크립트 공부 시작 ㅎㅎ
https://www.javascript.com/ 
위 사이트 1챕터 했음 ㅎㅎ

**Comment by magarage** [comment]
@serin9 스칼라는 안하는걸롱?
나는 팀에서 저번에 얘기한 스칼라 함수형 프로그래밍 스터디 시작했옹(엄청어렵다는..)

**Comment by serin9** [comment]
@magarage
그것도 하고싶긴한데 ㅎㅎㅎ
해야져 ㅎㅎㅎ
